### ISSUE TITLE
How to submit the form?

### ISSUE THREAD

**Issue by jankal** [formslider/jquery.formslider#21]
I added `action` and `method` attributes to my `<form>`-Tag.
When clicking a `<input type="submit" />`, nothing happens (`form.submit` is prevented by jquery.formslider).

How do I submit my form?

**Comment by tomhanoldt** [comment]
Via the FormSubmission-Plugin: https://github.com/formslider/jquery.formslider/blob/master/docs/PLUGINS.md#formsubmission

**Comment by jankal** [comment]
@tomhanoldt Thanks very much! Can I disable this behaviour in any way?

**Comment by tomhanoldt** [comment]
You can use the submission adapter FormSubmitterSubmit which doesn't stop the submit event (https://github.com/formslider/jquery.formslider/blob/master/src/coffee/plugins/form/form_submitter/submit.coffee) I think. 

I'm not sure if its well tested with the newly integrated validation, if you experience issues please reopen and I will take time for specs and integration tests or fee l free to contribute @jankal =)

**Comment by tomhanoldt** [comment]
You can also remove the FormSubmission-Plugin if you don't need deeper control of submissions.

**Comment by jankal** [comment]
How do I do that? - I just initialized the Plugin using
```
(function($){$('.formslider-wrapper').formslider();})(jQuery);
```

**Comment by tomhanoldt** [comment]
Oh, you have to override the default plugin configuration with your specific needed set like:
```js
(function($){

  $('.formslider-wrapper').formslider({
    plugins: [
      {
        class: 'FormSubmission'
        config:{
          submitter: {
            class: 'FormSubmitterSubmit'
          }
        },
       ...
    }
    ]
  });

})(jQuery);
```
In this case, if you override default plugins, you have to define the hole set of plugins you need like here: https://github.com/formslider/jquery.formslider/blob/master/dist/formslider.js#L2193

Have also a look at the documentation: https://github.com/formslider/jquery.formslider/blob/master/docs/INTEGRATION.md

And then the specific plugins:
https://github.com/formslider/jquery.formslider/blob/master/docs/PLUGINS.md

**Comment by tomhanoldt** [comment]
I highly recommend to write your integration with coffee script as your code gets clearer, same default configuration in coffee script: https://github.com/formslider/jquery.formslider/blob/master/src/coffee/formslider.coffee#L131

**Comment by tomhanoldt** [comment]
Ok I think the default behaviour should be the natural form submitter as people expect this to work. I reopen this bug and will change this with the next release next week.

Thanks for you hint @jankal

**Comment by tomhanoldt** [comment]
natural form submit is now default, run bower update --save jquery.formslider
